#+ summary: Update query to take SPOs from statements and make them simple triples

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX HRAkda: <https://purl.humanatlas.io/graph/hra-kidney-disease-atlas>

INSERT {
  GRAPH HRAkda: {
    ?subject ?predicate ?object .
  }
}
WHERE {
  GRAPH HRAkda: {
    [] a rdf:Statement ;
      rdf:subject ?subject ;
      rdf:predicate ?predicate ;
      rdf:object ?object ;
      rdfs:isDefinedBy ?source ;
    .
  }
}
