#+ summary: Unique Kidney AS, CT, and B in HRA

PREFIX biolink: <https://w3id.org/biolink/vocab/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX kidney: <http://purl.obolibrary.org/obo/UBERON_0002113>
PREFIX HRA: <https://purl.humanatlas.io/collection/hra>

SELECT DISTINCT ?id (SAMPLE(?name) as ?name) (SAMPLE(?symbol) as ?symbol) (SAMPLE(?category) as ?category) (HRA: as ?provided_by)
FROM HRA:
WHERE {
  VALUES (?asctb_type ?category) {
    ("AS"^^xsd:string biolink:GrossAnatomicalStructure)
    ("CT"^^xsd:string biolink:Cell)
    ("BM"^^xsd:string biolink:Gene)
  }
  ?id ccf:ccf_asctb_type ?asctb_type ;
    rdfs:label ?name .

  # AS
  {
    ?id ccf:ccf_part_of ?object .
    ?id ccf:ccf_part_of* kidney: .
  }
  UNION
  # CT
  {
    [] a ccf:CellMarkerDescriptor ;
      ccf:primary_anatomical_structure ?as ;
      ccf:primary_cell_type ?id .
    ?as ccf:ccf_part_of* kidney: .
  }
  UNION
  # BM
  {
    [] a ccf:CellMarkerDescriptor ;
      ccf:primary_anatomical_structure ?as ;
      ccf:biomarker ?id .
    ?as ccf:ccf_part_of* kidney: .

    ?id rdfs:label ?symbol .
  }
}
GROUP BY ?id
ORDER BY ?id
