PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?type (COUNT(*) AS ?count)
FROM <https://purl.humanatlas.io/graph/hra-kidney-disease-atlas>
WHERE {
  [] a rdf:Statement ;
    rdf:predicate ?type .
}
GROUP BY ?type
ORDER BY DESC(?count)
