PREFIX biolink: <https://w3id.org/biolink/vocab/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?class (COUNT(DISTINCT(?s)) AS ?count)
FROM <https://purl.humanatlas.io/graph/hra-kidney-disease-atlas>
WHERE {
  ?s a biolink:NamedThing ;
    a ?class .
  FILTER(?class != biolink:NamedThing)
}
GROUP BY ?class
ORDER BY DESC(?count)
